### ISSUE TITLE
Get Show information using IMDB

### ISSUE THREAD

**Issue by OstlerDev** [Codeusa/Strike#11]
Hey, I figured I would post this over here so you could better keep track of it:

Currently you need to pull the Title from the TV show then display then pull from the GetStrike database using the title. It would be a lot easier and would gain wider implementation (from Popcorn Time, as well as my own project) if there was a way to lookup the TV show by IMDB ID.

Something similar to this would be the best way (for me at least):

```
https://getstrike.net/api/v2/torrents/tv/?imdb=tt0944947
```

You had commented on an issue of mine that you would be working on it, so I just wanted to follow up with you and give you a better way to report the status or things that way. (Link to issue: https://github.com/OstlerDev/PopcornTV/issues/36 )

Thanks for all the awesome work you do!
- OstlerDev

**Comment by andrewmd5** [comment]
https://getstrike.net/api/v2/torrents/tv/?imdb=tt0944947

There you go
