### ISSUE TITLE
Apiary documentation

### ISSUE THREAD

**Issue by wolfhechel** [Codeusa/Strike#15]
It would be awesome to have a more structured API documentation since the current one is kind of outdated, all API documentation resides on four different pages (Main API, two blog posts and an Issue here on Github).

I would volunteer to write this up with your permission of course.

**Comment by andrewmd5** [comment]
If you wish to write up documentation I will have no problem including it

**Comment by wolfhechel** [comment]
Right, so I've written together the initial structure of the documentation, you can see it here; http://docs.test683.apiary.io/

The best part of apiary is that you can link a github repository and work with the documentation with git revisioning.

I also noticed that the /torrents/tv/ endpoint doesn't resolve titles anymore so I didn't include it.
