### ISSUE TITLE
Question: Are results paginated?

### ISSUE THREAD

**Issue by jonlunsford** [Codeusa/Strike#17]
Hi, apologies for opening an issue for a question, i'm not sure where to find this info. Are results from the search endpoint paginated? For example searching for "YIFY" on the site returns 1000 results, but searching via: `https://getstrike.net/api/v2/torrents/search/?phrase=YIFY` returns results limited to 100. There doesn't seem to be a page param, as `https://getstrike.net/api/v2/torrents/search/?phrase=YIFY&page=2` returns the same 100 results. 

If there is a page param, is it named something else?

Thanks again for creating awesome stuff!

**Comment by andrewmd5** [comment]
We limit the results currently cost of hosting cost, we offer keys for unlimited results if they're really needed.

**Comment by jonlunsford** [comment]
Ah I see. Well I can get by in the mean time. Thanks!
