### ISSUE TITLE
Include support for MPV

### ISSUE THREAD

**Issue by ghost** [Codeusa/Strike#2]
It would be cool to support MPV somehow, since it's cross platform and I think it can drop in to replace MPC with not too much difficulty. (at least from a cursory glance at the documentation.) I use MPV instead of VLC or mPlayer since it's just a better app imho.

http://mpv.io

EDIT: some info on the JSON IPC protocol:

http://mpv.io/manual/master/#json-ipc

For example of implementation in live app see: https://github.com/np1/mps-youtube

**Comment by andrewmd5** [comment]
Hi, I'll look into adding support for this, the challenge is going to be not external, but remote usage as Strike is strictly an android application.

This will be added to the TODO for the next version.

**Comment by ghost** [comment]
Ok cool!

**Comment by andrewmd5** [comment]
@nikkiii  any thoughts on this?

**Comment by ghost** [comment]
Closing this to clean up my open issues pool, also because I have no need for this, vlc is fine working with strike, and I don't use Strike anymore.
