### ISSUE TITLE
Imdb/Tvdb

### ISSUE THREAD

**Issue by PedroMCostaAndrade** [Codeusa/Strike#3]
Could you provide the imdb and tvdb id for movies and series?

**Comment by andrewmd5** [comment]
So you can do 

https://getstrike.net/api/v2/torrents/info/?hashes=ED70C185E3E3246F30B2FDB08D504EABED5EEA3F

Which will return the imdbid for anything in the movie/tv category

or if you just need the imdbid

https://getstrike.net/api/v2/torrents/imdb/?hash=ED70C185E3E3246F30B2FDB08D504EABED5EEA3F

and if you want imdb info

https://getstrike.net/api/v2/media/imdb/?imdbid=tt1520211

**Comment by heedrox** [comment]
would it be possible to search through imdbID?

**Comment by andrewmd5** [comment]
What do you mean by search?

**Comment by maelswarm** [comment]
Searching with imdbID would be pretty cool.

**Comment by andrewmd5** [comment]
I take it you mean returning a list of torrents that have the same imdbid?

**Comment by maelswarm** [comment]
That's what we're thinking.

**Comment by andrewmd5** [comment]
Only issue is imdbs are fetched when requested and not something that is currently fully populated; so you could potentially be missing some, nonetheless i'll add it.

**Comment by heedrox** [comment]
cool !

**Comment by blakeembrey** [comment]
@Codeusa Any news on searching for torrents by IMDB ID? I would love to play around with it.

**Comment by andrewmd5** [comment]
https://getstrike.net/api/v2/torrents/tv/?imdb=tt0944947

http://blog.getstrike.net/post/121229490218/new-tv-endpoints-beta

Pretty rough at the moment as I clean up A LOT of my databases and get formatting down

**Comment by blakeembrey** [comment]
Thanks for the reply. I saw that post but I was curious if it could query movies too. It looks like a lot of missing torrents using that endpoint for now. For TV shows, what about querying by both IMDB ID and season/episode or allowing a query/title for trying to drill down to the season/episode?

I only started exploring the API today, but would love to use it if I can.

**Comment by andrewmd5** [comment]
IF you wish to create a separate issue with all your seeds i can get on top
of it

**Comment by blakeembrey** [comment]
@Codeusa Sure, no worries. Just didn't want to duplicate issues since this mentions both.

**Comment by wolfhechel** [comment]
Is it possible to search by imdb? As far as I can see it's only usable for tv-shows and episodes?

**Comment by micshome** [comment]
https://getstrike.net - Not working, redirects to ADS

**Comment by andrewmd5** [comment]
ADS? Strike has been shut down for some time, Ulterius is my primary focus.
