### ISSUE TITLE
.onion site?

### ISSUE THREAD

**Issue by maelswarm** [Codeusa/Strike#6]

**Comment by andrewmd5** [comment]
Sure I can set this up

**Comment by maelswarm** [comment]
On a separate server? I'd be willing to donate.

**Comment by andrewmd5** [comment]
The onion site probably won't get crazy traffic, but I can guarantee the
same results; if you're willing to donate I can get a dedicated server for
the onion site for about 35$ a month that fits our needs.

**Comment by maelswarm** [comment]
True.
I'm down for the server, if we can get a couple others to donate.

**Comment by joe-arenas** [comment]
What is this .onion just the domain?

**Comment by maelswarm** [comment]
[https://en.wikipedia.org/wiki/.onion](https://en.wikipedia.org/wiki/.onion)

**Comment by maelswarm** [comment]
Can we get this up purty please.
