### ISSUE TITLE
Download torrent from api

### ISSUE THREAD

**Issue by Hellowlol** [Codeusa/Strike#9]
I if have understood the api docs correctly you can call:

https://getstrike.net/api/v2/torrents/download/?hash=0EB6605E041F1846B84BAA63346012A82706A95D

to download a torrent. However if i do that it returns:

{"statuscode":200,"message":"https://getstrike.net/torrents/api/download/0EB6605E041F1846B84BAA63346012A82706A95D.torrent"}

Is this a bug or am i reading this wrong?

**Comment by andrewmd5** [comment]
The endpoint checks if the torrent exisit on the disk; if it doesn't it downloads it, if it fails to it would return 404, else it returns a link to the torrent for you to then download, that being the message.

**Comment by Hellowlol** [comment]
Ah, thanks!
